### ISSUE TITLE
Delete one word to the right of cursor

### ISSUE THREAD

**Issue by hurl** [GabLeRoux/iterm2-macos-dynamic-profile#2]
I think the code for "Delete one word to the right of the cursor" is missing from the JSON file. Specifically: `⌥+fn←Delete` or `⌥+Delete→` Send Hex Codes: `0x1b 0x64`.

Adding this to the JSON file works for me:
```json
        "0xf728-0x80000" : {
          "Action" : 11,
          "Text" : "0x1b 0x64"
        }
```

Thanks for this resource.

**Comment by GabLeRoux** [comment]
Thanks, here we go :)

**Comment by GabLeRoux** [comment]
hmm, I tried deleting the dynamic profile, importing it again, but I still see `Send Hex Codes: 0x0b` with `⌥+Delete→`

![image](https://user-images.githubusercontent.com/1264761/73569860-3dddeb80-4439-11ea-8304-a87ea06577a9.png)

I find it a bit weird

**Comment by GabLeRoux** [comment]
Ah nevermind, I wasn't on `master` branch when testing ahah, works fine, thanks 👍 

![image](https://user-images.githubusercontent.com/1264761/73570120-be9ce780-4439-11ea-8bb7-e42f469d4e3c.png)
